package com.propergentleman.tickle;

import com.intellij.lexer.FlexAdapter;

public class TclLexerAdapter extends FlexAdapter {
    public TclLexerAdapter() {
        super(new TclLexer(null));
    }
}

// Note: TclLexer would be your lexer implementation, typically generated by JFlex.
